### ISSUE TITLE
[BUG] Caught exception: System.InvalidOperationException: Sequence contains no elements

### ISSUE THREAD

**Issue by elior99** [yairp03/HoradotTV#163]
Get exception when trying to download:
Caught exception: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.MaxInteger[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source, Func`2 selector)
   at HoradotTV.Console.Program.DownloadMedia(IEnumerable`1 mediaToDownload, String downloadLocation, Boolean rootRun)
   at HoradotTV.Console.Program.DownloadMedia(IEnumerable`1 mediaToDownload, String downloadLocation, Boolean rootRun)

Doesn't matter if i select to download episode or season or show it happens.
Version 2.0.0

**Comment by yairp03** [comment]
It probably happaned because the show has empty season.
Please add the exact input you gave the software so I can trigger the exception and fix it.
